apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-customer-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: Customer
  POSTGRES_USER: User
  POSTGRES_PASSWORD: Password

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-customer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-customer-deploy
  template:
    metadata:
      labels:
        app: pg-customer-deploy
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod 0700 /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: azure
      containers:
        - name: postgres
          image: 'postgres:17'
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-customer-configmap
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: azure
              subPath: customer
      volumes:
        - name: azure
          csi:
            driver: file.csi.azure.com
            volumeAttributes:
              secretName: azure-secret
              shareName: db-production
              mountOptions: 'dir_mode=0700,file_mode=0700,uid=999,gid=999,cache=strict,actimeo=30,nosharesock,nobrl'
---
apiVersion: v1
kind: Service
metadata:
  name: pg-customer-service
  labels:
    app: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: pg-customer-deploy