apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-media-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: Media
  POSTGRES_USER: User
  POSTGRES_PASSWORD: Password

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-media
spec:
  serviceName: "pg-media-service"
  replicas: 1
  selector:
    matchLabels:
      app: pg-media
  template:
    metadata:
      labels:
        app: pg-media
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod 0700 /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      containers:
        - name: postgres
          image: 'postgres:17'
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-media-configmap
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
              subPath: media
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pg-media-service
  labels:
    app: postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: pg-media