apiVersion: v1
kind: Secret
metadata:
  name: pg-order-secret
type: Opaque
data:
  connectionstring: SG9zdD1wZy1vcmRlci1zZXJ2aWNlO0RhdGFiYXNlPW9yZGVyO1VzZXJuYW1lPVVzZXI7UGFzc3dvcmQ9UGFzc3dvcmQ=
  # Generate: echo -n "Host=pg-order-service;Database=order;Username=User;Password=Password" | base64

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-order-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: Order
  POSTGRES_USER: User
  POSTGRES_PASSWORD: Password

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-order
spec:
  serviceName: "pg-order"
  replicas: 1
  selector:
    matchLabels:
      app: pg-order
  template:
    metadata:
      labels:
        app: pg-order
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod 0700 /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      containers:
        - name: postgres
          image: 'postgres:17'
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-order-configmap
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
              subPath: order
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pg-order-service
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: pg-order

