apiVersion: v1
kind: Secret
metadata:
  name: pg-product-secret
type: Opaque
data:
  connectionstring: SG9zdD1wZy1wcm9kdWN0LXNlY3JldDtEYXRhYmFzZT1Qcm9kdWN0O1VzZXJuYW1lPVVzZXI7UGFzc3dvcmQ9UGFzc3dvcmQ=
  # Generate: echo -n "Host=pg-product-secret;Database=Product;Username=User;Password=Password" | base64

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-product-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: Product
  POSTGRES_USER: User
  POSTGRES_PASSWORD: Password

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-product-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-product-deploy
  template:
    metadata:
      labels:
        app: pg-product-deploy
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chmod 0700 /var/lib/postgresql/data && chown -R 999:999 /var/lib/postgresql/data"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: azure
      containers:
        - name: postgres
          image: 'postgres:17'
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-product-configmap
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: azure
              subPath: product
      volumes:
        - name: azure
          csi:
            driver: file.csi.azure.com
            volumeAttributes:
              secretName: azure-secret
              shareName: saboobo-azfile
              mountOptions: 'dir_mode=0700,file_mode=0700,uid=999,gid=999,cache=strict,actimeo=30,nosharesock,nobrl'
---
apiVersion: v1
kind: Service
metadata:
  name: pg-product-service
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: pg-product-deploy