apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: saboobo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: saboobo-azfile-sc
  csi:
    driver: file.csi.azure.com
    volumeHandle: "saboobo-rg#sabboboac#saboobo-azfile"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      shareName: saboobo-azfile
    nodeStageSecretRef: 
      name: azure-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=999
    - gid=999
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks