apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: c2FiYm9ib2Fj  # Base64 encoded value of myAKSStorageAccount - echo -n "myAKSStorageAccount" | base64
  azurestorageaccountkey: YW9XeElvVnFOOTV1S3lzYW5HR3J6N3o4SEV1anZQSjBmVkVkaGVuclJaeEJ5QXVXVWxKTnBlSWVNWnVPY2FIWHBwZTkvaXRDNHRNdytBU3RlREhuOWc9PQ==  # Base64 encoded value of $STORAGE_KEY - echo -n "$STORAGE_KEY" | base64
