apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azfile-pvc
spec:
  accessModes:
    - ReadWriteMany
  #storageClassName: ""
  #volumeName: azfile-pv
  resources:
    requests:
      storage: 1Gi