apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azfile-saboobo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-azurefile
  csi:
    driver: file.csi.azure.com
    volumeHandle: "saboobo-rg/sabboboac/saboobo-azfile"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      shareName: saboobo-azfile # File share in Storage Account
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  # azureFile:
  #   secretName: azure-secret
  #   shareName: saboobo-azfile
  #   readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl  # disable sending byte range lock requests to the server and for applications which have challenges with posix locks